# -*- mode: ruby -*-
# vi: set ft=ruby :

vmbox = "puppetlab-centos-64-nocm"
vmboxurl = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210-nocm.box"

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = vmbox
  config.vm.box_url = vmboxurl
  config.vm.provision :shell, :path => "provision.sh"

end
